Info<< "Reading field fi\n" << endl;

volScalarField fi
(
IOobject
(
    "fi",
    runTime.timeName(),
    mesh,
    IOobject::MUST_READ,
    IOobject::AUTO_WRITE
),
mesh
);

volScalarField Flux
(
IOobject
(
    "Flux",
    runTime.timeName(),
    mesh,
    IOobject::NO_READ,
    IOobject::NO_WRITE//AUTO_WRITE
),
mesh,
dimensionedScalar("0", dimensionSet(0,-2,0,0,0,1,0), 0.0)
);



Info<< "Reading transportProperties\n" << endl;

IOdictionary transportProperties
(
IOobject
(
    "transportProperties",
    runTime.constant(),
    mesh,
    IOobject::MUST_READ_IF_MODIFIED,
    IOobject::NO_WRITE
)
);


Info<< "Reading diffusivity kf\n" << endl;

dimensionedScalar kf
(
transportProperties.lookup("kf")
);

volScalarField keff
(
IOobject
(
    "keff",
    runTime.timeName(),
    mesh,
    IOobject::MUST_READ_IF_MODIFIED,//MUST_READ,
    IOobject::AUTO_WRITE
),
mesh,
dimensionedScalar("keff",kf)
);
    
    
Info<< "Reading controlProperties\n" << endl;

IOdictionary controlProperties
(
    IOobject
    (
	"controlProperties",
	runTime.constant(),
	mesh,
	IOobject::MUST_READ_IF_MODIFIED,
	IOobject::NO_WRITE
    )
);

IOdictionary Results
(
    IOobject
    (
	"Results",
	runTime.constant(),
	mesh,
	IOobject::MUST_READ_IF_MODIFIED,
	IOobject::AUTO_WRITE
    )
);

